import type { OCRExecutionRecord } from "./ocrExecutionWorkspace.contracts";

export const SEED_OCR_EXECUTION_RECORDS: OCRExecutionRecord[] = [
  {
    queue: {
      id: "OCR-240531-001",
      title: "Apex Castings invoice batch",
      supplier: "Apex Castings",
      source: "Invoice intake",
      assignee: "Riya",
      pages: 3,
      fieldCount: 18,
      completedFields: 14,
      confidence: 0.78,
      anomalyCount: 2,
      queueState: "processing",
      workflowState: "in-review",
      reviewState: "low-confidence",
      lastUpdated: "2026-05-26T08:10:00+05:30",
      priority: "critical",
    },
    document: {
      id: "doc-apex-001",
      title: "INV-8891 / Apex Castings",
      pages: [
        { id: "doc-apex-001-page-1", pageNumber: 1, title: "Invoice Header", completeness: 0.82, status: "pending" },
        { id: "doc-apex-001-page-2", pageNumber: 2, title: "Line Items", completeness: 0.74, status: "in-review" },
        { id: "doc-apex-001-page-3", pageNumber: 3, title: "Tax Summary", completeness: 0.93, status: "ready" },
      ],
    },
    boundingBoxes: [
      { id: "apex-bb-1", pageId: "doc-apex-001-page-1", x: 12, y: 10, width: 28, height: 8, confidence: 0.94, label: "Invoice No", reviewState: "reviewed" },
      { id: "apex-bb-2", pageId: "doc-apex-001-page-1", x: 58, y: 14, width: 18, height: 7, confidence: 0.63, label: "Invoice Date", reviewState: "flagged", anomaly: true },
      { id: "apex-bb-3", pageId: "doc-apex-001-page-2", x: 10, y: 28, width: 74, height: 34, confidence: 0.71, label: "Line Grid", reviewState: "unreviewed" },
      { id: "apex-bb-4", pageId: "doc-apex-001-page-3", x: 62, y: 70, width: 19, height: 9, confidence: 0.89, label: "Grand Total", reviewState: "reviewed" },
    ],
    extractionFields: [
      { id: "apex-field-1", label: "Invoice Number", value: "INV-8891", confidence: 0.94, reviewState: "reviewed", pageId: "doc-apex-001-page-1", boundingBoxId: "apex-bb-1", meta: "Matched against supplier pattern" },
      { id: "apex-field-2", label: "Invoice Date", value: "26/05/2026", confidence: 0.63, reviewState: "flagged", pageId: "doc-apex-001-page-1", boundingBoxId: "apex-bb-2", meta: "AI suggests 25/05/2026" },
      { id: "apex-field-3", label: "Supplier GSTIN", value: "29AAECA9821R1ZT", confidence: 0.88, reviewState: "reviewed", meta: "Cross-check passed" },
      { id: "apex-field-4", label: "PO Reference", value: "PO-78432", confidence: 0.73, reviewState: "unreviewed", meta: "Detected from line footer" },
      { id: "apex-field-5", label: "Invoice Total", value: "₹4,82,600", confidence: 0.89, reviewState: "reviewed", pageId: "doc-apex-001-page-3", boundingBoxId: "apex-bb-4", meta: "Total aligned with tax summary" },
      { id: "apex-field-6", label: "Freight Charge", value: "₹18,000", confidence: 0.68, reviewState: "flagged", meta: "Variance from PO terms" },
    ],
    aiRecommendations: [
      "Date field likely shifted by one row in the header stamp region.",
      "Freight charge is higher than the linked PO tolerance by 4.6%.",
      "Line item grid needs one human pass before approval.",
    ],
    workflowTimeline: [
      { id: "apex-step-1", label: "Intake queued", detail: "Document uploaded from AP inbox", status: "done", timestamp: "08:02" },
      { id: "apex-step-2", label: "AI extraction", detail: "18 fields parsed, 2 anomalies detected", status: "done", timestamp: "08:05" },
      { id: "apex-step-3", label: "Confidence review", detail: "Low-confidence fields routed to human reviewer", status: "current", timestamp: "08:10" },
      { id: "apex-step-4", label: "Operational approval", detail: "Awaiting reviewer confirmation", status: "pending", timestamp: "Pending" },
    ],
  },
  {
    queue: {
      id: "OCR-240531-002",
      title: "Mehta Metals GRN",
      supplier: "Mehta Metals",
      source: "GRN intake",
      assignee: "Arjun",
      pages: 2,
      fieldCount: 12,
      completedFields: 12,
      confidence: 0.93,
      anomalyCount: 0,
      queueState: "ready",
      workflowState: "approved",
      reviewState: "reviewed",
      lastUpdated: "2026-05-26T07:42:00+05:30",
      priority: "normal",
    },
    document: {
      id: "doc-mehta-002",
      title: "GRN-22071 / Mehta Metals",
      pages: [
        { id: "doc-mehta-002-page-1", pageNumber: 1, title: "GRN Header", completeness: 1, status: "approved" },
        { id: "doc-mehta-002-page-2", pageNumber: 2, title: "Received Items", completeness: 1, status: "approved" },
      ],
    },
    boundingBoxes: [
      { id: "mehta-bb-1", pageId: "doc-mehta-002-page-1", x: 14, y: 12, width: 22, height: 7, confidence: 0.96, label: "GRN No", reviewState: "reviewed" },
      { id: "mehta-bb-2", pageId: "doc-mehta-002-page-2", x: 10, y: 24, width: 75, height: 40, confidence: 0.91, label: "Received Grid", reviewState: "reviewed" },
    ],
    extractionFields: [
      { id: "mehta-field-1", label: "GRN Number", value: "GRN-22071", confidence: 0.96, reviewState: "reviewed", meta: "Validated against warehouse log" },
      { id: "mehta-field-2", label: "Supplier Name", value: "Mehta Metals", confidence: 0.97, reviewState: "reviewed", meta: "Master record match" },
      { id: "mehta-field-3", label: "Received Quantity", value: "420 units", confidence: 0.92, reviewState: "reviewed", meta: "No variance from PO" },
      { id: "mehta-field-4", label: "Dock Timestamp", value: "07:36", confidence: 0.93, reviewState: "reviewed", meta: "Synced to gate system" },
    ],
    aiRecommendations: [
      "No operational intervention required.",
      "Document can be pushed to completion without escalation.",
    ],
    workflowTimeline: [
      { id: "mehta-step-1", label: "Intake queued", detail: "GRN scan imported from dock terminal", status: "done", timestamp: "07:34" },
      { id: "mehta-step-2", label: "AI extraction", detail: "All fields parsed above threshold", status: "done", timestamp: "07:37" },
      { id: "mehta-step-3", label: "Operational approval", detail: "Reviewer approved without changes", status: "done", timestamp: "07:42" },
      { id: "mehta-step-4", label: "Workflow complete", detail: "Ready for downstream posting", status: "current", timestamp: "Live" },
    ],
  },
  {
    queue: {
      id: "OCR-240531-003",
      title: "Shivam Plastics invoice",
      supplier: "Shivam Plastics",
      source: "Invoice intake",
      assignee: "Neha",
      pages: 4,
      fieldCount: 21,
      completedFields: 9,
      confidence: 0.69,
      anomalyCount: 3,
      queueState: "blocked",
      workflowState: "blocked",
      reviewState: "anomaly",
      lastUpdated: "2026-05-26T08:21:00+05:30",
      priority: "critical",
    },
    document: {
      id: "doc-shivam-003",
      title: "INV-10291 / Shivam Plastics",
      pages: [
        { id: "doc-shivam-003-page-1", pageNumber: 1, title: "Header", completeness: 0.58, status: "blocked" },
        { id: "doc-shivam-003-page-2", pageNumber: 2, title: "Items", completeness: 0.47, status: "blocked" },
        { id: "doc-shivam-003-page-3", pageNumber: 3, title: "Items Continued", completeness: 0.51, status: "blocked" },
        { id: "doc-shivam-003-page-4", pageNumber: 4, title: "Tax Footer", completeness: 0.74, status: "blocked" },
      ],
    },
    boundingBoxes: [
      { id: "shivam-bb-1", pageId: "doc-shivam-003-page-1", x: 18, y: 11, width: 26, height: 7, confidence: 0.61, label: "Vendor Name", reviewState: "flagged", anomaly: true },
      { id: "shivam-bb-2", pageId: "doc-shivam-003-page-2", x: 12, y: 26, width: 72, height: 31, confidence: 0.58, label: "Item Grid", reviewState: "failed", anomaly: true },
      { id: "shivam-bb-3", pageId: "doc-shivam-003-page-4", x: 61, y: 72, width: 21, height: 8, confidence: 0.76, label: "Tax Total", reviewState: "unreviewed" },
    ],
    extractionFields: [
      { id: "shivam-field-1", label: "Vendor Name", value: "Shivam Plostic", confidence: 0.61, reviewState: "flagged", meta: "Possible OCR character swap" },
      { id: "shivam-field-2", label: "Invoice Number", value: "INV-10291", confidence: 0.87, reviewState: "reviewed", meta: "Pattern matched" },
      { id: "shivam-field-3", label: "Invoice Total", value: "₹7,18,200", confidence: 0.76, reviewState: "unreviewed", meta: "Tax total not reconciled" },
      { id: "shivam-field-4", label: "Line Item Count", value: "17", confidence: 0.55, reviewState: "failed", meta: "Grid extraction incomplete" },
      { id: "shivam-field-5", label: "Payment Terms", value: "Net 30", confidence: 0.72, reviewState: "unreviewed", meta: "Needs supplier validation" },
    ],
    aiRecommendations: [
      "Escalate to anomaly review because line grid extraction failed on page 2.",
      "Apply AI correction to vendor name before posting.",
      "Hold approval until tax footer reconciles with invoice total.",
    ],
    workflowTimeline: [
      { id: "shivam-step-1", label: "Intake queued", detail: "Invoice forwarded from supplier email", status: "done", timestamp: "08:09" },
      { id: "shivam-step-2", label: "AI extraction", detail: "Grid extraction failed on one page", status: "critical", timestamp: "08:16" },
      { id: "shivam-step-3", label: "Anomaly escalation", detail: "Waiting for reviewer decision", status: "current", timestamp: "08:21" },
      { id: "shivam-step-4", label: "Operational approval", detail: "Blocked until correction is applied", status: "pending", timestamp: "Blocked" },
    ],
  },
  {
    queue: {
      id: "OCR-240531-004",
      title: "Lakshmi Auto parts receipt",
      supplier: "Lakshmi Auto Parts",
      source: "Delivery challan",
      assignee: "Vikram",
      pages: 2,
      fieldCount: 10,
      completedFields: 7,
      confidence: 0.84,
      anomalyCount: 1,
      queueState: "queued",
      workflowState: "pending",
      reviewState: "suggested",
      lastUpdated: "2026-05-26T08:04:00+05:30",
      priority: "warning",
    },
    document: {
      id: "doc-lakshmi-004",
      title: "DC-55118 / Lakshmi Auto Parts",
      pages: [
        { id: "doc-lakshmi-004-page-1", pageNumber: 1, title: "Delivery Header", completeness: 0.83, status: "pending" },
        { id: "doc-lakshmi-004-page-2", pageNumber: 2, title: "Item Receipt", completeness: 0.79, status: "pending" },
      ],
    },
    boundingBoxes: [
      { id: "lakshmi-bb-1", pageId: "doc-lakshmi-004-page-1", x: 15, y: 13, width: 20, height: 7, confidence: 0.88, label: "Challan No", reviewState: "reviewed" },
      { id: "lakshmi-bb-2", pageId: "doc-lakshmi-004-page-2", x: 13, y: 29, width: 70, height: 35, confidence: 0.74, label: "Receipt Grid", reviewState: "corrected" },
    ],
    extractionFields: [
      { id: "lakshmi-field-1", label: "Challan Number", value: "DC-55118", confidence: 0.88, reviewState: "reviewed", meta: "Matched receipt sequence" },
      { id: "lakshmi-field-2", label: "Warehouse Bay", value: "Bay 03", confidence: 0.8, reviewState: "corrected", meta: "AI suggested Bay 08" },
      { id: "lakshmi-field-3", label: "Received Quantity", value: "86 units", confidence: 0.84, reviewState: "unreviewed", meta: "One line still pending verification" },
      { id: "lakshmi-field-4", label: "Inspector Initials", value: "VK", confidence: 0.66, reviewState: "flagged", meta: "Handwriting confidence low" },
    ],
    aiRecommendations: [
      "One handwriting-derived field should be validated before completion.",
      "Receipt grid has already accepted one AI correction successfully.",
    ],
    workflowTimeline: [
      { id: "lakshmi-step-1", label: "Intake queued", detail: "Delivery challan scanned at receipt desk", status: "done", timestamp: "07:58" },
      { id: "lakshmi-step-2", label: "AI extraction", detail: "Initial pass completed with one suggestion", status: "done", timestamp: "08:01" },
      { id: "lakshmi-step-3", label: "Human review", detail: "Awaiting final handwriting validation", status: "current", timestamp: "08:04" },
      { id: "lakshmi-step-4", label: "Workflow complete", detail: "Ready after final check", status: "pending", timestamp: "Pending" },
    ],
  },
];
