import type { Config } from "tailwindcss";

const semanticColors = {
  surface: {
    app: "var(--surface-app)",
    shell: "var(--surface-shell)",
    panel: "var(--surface-panel)",
    card: "var(--surface-card)",
    elevated: "var(--surface-elevated)",
    overlay: "var(--surface-overlay)",
    hover: "var(--surface-hover)",
    active: "var(--surface-active)",
    selected: "var(--surface-selected)",
    skeleton: "var(--surface-skeleton)",
    "skeleton-shine": "var(--surface-skeleton-shine)",
  },
  text: {
    primary: "var(--text-primary)",
    secondary: "var(--text-secondary)",
    tertiary: "var(--text-tertiary)",
    disabled: "var(--text-disabled)",
    inverse: "var(--text-inverse)",
    link: "var(--text-link)",
    "link-hover": "var(--text-link-hover)",
    danger: "var(--text-danger)",
    success: "var(--text-success)",
    warning: "var(--text-warning)",
  },
  border: {
    subtle: "var(--border-subtle)",
    default: "var(--border-default)",
    secondary: "var(--color-border-secondary)",
    strong: "var(--border-strong)",
    focus: "var(--border-focus)",
    danger: "var(--border-danger)",
    success: "var(--border-success)",
  },
  action: {
    primary: "var(--action-primary)",
    "primary-hover": "var(--action-primary-hover)",
    "primary-active": "var(--action-primary-active)",
    "primary-text": "var(--action-primary-text)",
    secondary: "var(--action-secondary)",
    "secondary-hover": "var(--action-secondary-hover)",
    "secondary-border": "var(--action-secondary-border)",
    "secondary-text": "var(--action-secondary-text)",
    "ghost-hover": "var(--action-ghost-hover)",
    destructive: "var(--action-destructive)",
    "destructive-hover": "var(--action-destructive-hover)",
    disabled: "var(--action-disabled)",
    "disabled-text": "var(--action-disabled-text)",
  },
  status: {
    success: {
      fg: "var(--status-success-fg)",
      bg: "var(--status-success-bg)",
      border: "var(--status-success-border)",
      icon: "var(--status-success-icon)",
    },
    warning: {
      fg: "var(--status-warning-fg)",
      bg: "var(--status-warning-bg)",
      border: "var(--status-warning-border)",
      icon: "var(--status-warning-icon)",
    },
    danger: {
      fg: "var(--status-danger-fg)",
      bg: "var(--status-danger-bg)",
      border: "var(--status-danger-border)",
      icon: "var(--status-danger-icon)",
    },
    processing: {
      fg: "var(--status-processing-fg)",
      bg: "var(--status-processing-bg)",
      border: "var(--status-processing-border)",
      icon: "var(--status-processing-icon)",
    },
    paused: {
      fg: "var(--status-paused-fg)",
      bg: "var(--status-paused-bg)",
      border: "var(--status-paused-border)",
      icon: "var(--status-paused-icon)",
    },
    inactive: {
      fg: "var(--status-inactive-fg)",
      bg: "var(--status-inactive-bg)",
      border: "var(--status-inactive-border)",
      icon: "var(--status-inactive-icon)",
    },
    draft: {
      fg: "var(--status-draft-fg)",
      bg: "var(--status-draft-bg)",
      border: "var(--status-draft-border)",
      icon: "var(--status-draft-icon)",
    },
    synced: {
      fg: "var(--status-synced-fg)",
      bg: "var(--status-synced-bg)",
      border: "var(--status-synced-border)",
      icon: "var(--status-synced-icon)",
    },
    info: {
      fg: "var(--status-info-fg)",
      bg: "var(--status-info-bg)",
      border: "var(--status-info-border)",
      icon: "var(--status-info-icon)",
    },
  },
  workflow: {
    active: "var(--workflow-active)",
    "active-bg": "var(--workflow-active-bg)",
    complete: "var(--workflow-complete)",
    "complete-bg": "var(--workflow-complete-bg)",
    blocked: "var(--workflow-blocked)",
    "blocked-bg": "var(--workflow-blocked-bg)",
    pending: "var(--workflow-pending)",
    "pending-bg": "var(--workflow-pending-bg)",
    "ai-processing": "var(--workflow-ai-processing)",
    "ai-bg": "var(--workflow-ai-bg)",
  },
  // Sprint 2 Task 4: Calm indigo tokens for AI processing surfaces.
  // Exposes utilities like bg-ai-processing-bg, text-ai-processing-fg,
  // border-ai-processing-border for AI insight panels.
  "ai-processing": {
    bg: "var(--ai-processing-bg)",
    fg: "var(--ai-processing-fg)",
    border: "var(--ai-processing-border)",
  },
  confidence: {
    "high-fg": "var(--confidence-high-fg)",
    "medium-fg": "var(--confidence-medium-fg)",
    "low-fg": "var(--confidence-low-fg)",
  },
  command: {
    bg: "var(--command-bg)",
    panel: "var(--command-panel-bg)",
    border: "var(--command-border)",
    hover: "var(--command-hover)",
    active: "var(--command-active)",
    selected: "var(--command-selected)",
    match: "var(--command-match-highlight)",
    shortcut: "var(--command-shortcut-muted)",
    danger: "var(--command-danger)",
  },
} as const;

const config: Config = {
  content: ["./src/**/*.{ts,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        ...semanticColors,
        background: "var(--surface-app)",
        foreground: "var(--text-primary)",
        base: "var(--bg)",
        card: "var(--card)",
        textLegacy: "var(--text)",
        muted: "var(--muted)",
        accent: "var(--accent)",
      },
      spacing: {
        px: "var(--space-px)",
        0: "var(--space-0)",
        0.5: "var(--space-0-5)",
        1: "var(--space-1)",
        1.5: "var(--space-1-5)",
        2: "var(--space-2)",
        2.5: "var(--space-2-5)",
        3: "var(--space-3)",
        3.5: "var(--space-3-5)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        9: "var(--space-9)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        14: "var(--space-14)",
        16: "var(--space-16)",
        20: "var(--space-20)",
        24: "var(--space-24)",
        xs: "var(--space-xs)",
        sm: "var(--space-sm)",
        md: "var(--space-md)",
        lg: "var(--space-lg)",
        xl: "var(--space-xl)",
        "2xl": "var(--space-2xl)",
        "badge-x": "var(--density-badge-pad-x)",
        "badge-y": "var(--density-badge-pad-y)",
        "cell-x": "var(--density-cell-pad-x)",
        "cell-y": "var(--density-cell-pad-y)",
        "density-gap": "var(--density-gap)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
        numeric: ["var(--font-numeric)"],
      },
      fontSize: {
        "2xs": ["var(--text-2xs)", { lineHeight: "var(--leading-snug)" }],
        xs: ["var(--text-xs)", { lineHeight: "var(--leading-snug)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--leading-normal)" }],
        base: ["var(--text-base)", { lineHeight: "var(--leading-normal)" }],
        md: ["var(--text-md)", { lineHeight: "var(--leading-normal)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--leading-tight)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--leading-tight)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--leading-tight)" }],
        "3xl": ["var(--text-3xl)", { lineHeight: "var(--leading-none)" }],
        label: ["var(--type-label)", { lineHeight: "var(--leading-snug)" }],
        "label-dense": ["var(--type-label-dense)", { lineHeight: "var(--leading-snug)" }],
        body: ["var(--type-body)", { lineHeight: "var(--leading-normal)" }],
        "table-cell": ["var(--type-table-cell)", { lineHeight: "var(--leading-snug)" }],
        "table-header": ["var(--type-table-header)", { lineHeight: "var(--leading-snug)" }],
        "panel-title": ["var(--type-panel-title)", { lineHeight: "var(--leading-tight)" }],
        "page-title": ["var(--type-page-title)", { lineHeight: "var(--leading-tight)" }],
        "numeric-lg": ["var(--type-numeric-lg)", { lineHeight: "var(--leading-none)" }],
        "numeric-md": ["var(--type-numeric-md)", { lineHeight: "var(--leading-tight)" }],
        "numeric-sm": ["var(--type-numeric-sm)", { lineHeight: "var(--leading-snug)" }],
        status: ["var(--type-status)", { lineHeight: "var(--leading-snug)" }],
        "table-density": ["var(--density-font-table)", { lineHeight: "var(--leading-snug)" }],
        code: ["var(--type-code)", { lineHeight: "var(--leading-snug)" }],
        timestamp: ["var(--type-timestamp)", { lineHeight: "var(--leading-snug)" }],
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        control: "var(--radius-sm)",
        panel: "var(--radius-md)",
        overlay: "var(--radius-lg)",
        badge: "var(--radius-xs)",
      },
      boxShadow: {
        inset: "var(--shadow-inset)",
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        soft: "var(--shadow-sm)",
      },
      zIndex: {
        base: "var(--z-base)",
        raised: "var(--z-raised)",
        sticky: "var(--z-sticky)",
        "overlay-bg": "var(--z-overlay-bg)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
        command: "var(--z-command)",
        toast: "var(--z-toast)",
        tooltip: "var(--z-tooltip)",
      },
      height: {
        row: "var(--density-row-height)",
        "row-lg": "var(--density-row-height-lg)",
        input: "var(--density-input-height)",
        button: "var(--density-btn-height)",
        icon: "var(--density-icon-size)",
        "table-sm": "calc(var(--density-row-height-lg) * 8)",
        "table-md": "calc(var(--density-row-height-lg) * 12)",
        "table-lg": "calc(100dvh - 200px)",
      },
      minHeight: {
        row: "var(--density-row-height)",
        "row-lg": "var(--density-row-height-lg)",
        input: "var(--density-input-height)",
        button: "var(--density-btn-height)",
        textarea: "calc(var(--density-row-height-lg) * 2)",
      },
      maxHeight: {
        "table-sm": "calc(var(--density-row-height-lg) * 8)",
        "table-md": "calc(var(--density-row-height-lg) * 12)",
        "table-lg": "calc(100dvh - 200px)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        base: "var(--motion-base)",
        moderate: "var(--motion-moderate)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        decelerate: "var(--ease-decelerate)",
        accelerate: "var(--ease-accelerate)",
      },
    },
  },
  plugins: [],
};

export default config;
